blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name = 'index'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^contact/$', views.contact, name='contact'),
                       url(r'^(?P<post_slug>[\w-]+)/$', views.view_post, name='view_post'))

website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^blog/', include('blog.urls', namespace='blog')),
                        url(r'^', include('blog.urls', namespace='blog')),

    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
import datetime


# Create your models here.
class Post(models.Model):
    title_text = models.CharField(max_length = 500)
    pub_date = models.DateTimeField('date published')
    content =  models.TextField()
    slug = models.SlugField(max_length=100, db_index=True, blank=True)

    #methods
    def __unicode__(self):
        return self.title_text + "\n"+ self.pub_date.__str__() + "\n" + self.content
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title_text)    #newly created object, set slug
        super(Post, self).save(*args, **kwargs)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'




    

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from  blog.models import Post
from django.template import RequestContext, loader
from django.template.defaultfilters import slugify
import urllib2 #to convert url to title string
import pdb; 
# Create your views here.

def index(request):
    post_list = Post.objects.order_by('-pub_date')
    context = {'post_list': post_list}
    return render(request, 'blog/index.djhtml', context)


def view_post(request, post_slug):

    #original method of unslugifying alone will fail if any symbols like commas and colons
    #are in title, 

    try:
      
        post = Post.objects.get(slug=post_slug) #set to lower first


    except Post.DoesNotExist:
        raise Http404("Post does not exist")

    return render(request, 'blog/posts.djhtml', {'post': post})


def about(request):
    """
    View for the about page
    """
    return render(request, 'blog/about.djhtml')
def contact(request):
    """
    view for the contact page
    """
    return render(request, 'blog/contact.djhtml')

blog/templates/blog/index.html
{% load staticfiles %}
  <!-- <h1>Welcome to Programmer Plebeian </h1>
  <h2>A Budding Programmer's Paradise</h2> -->

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Programmer Plebeian</title>
  <meta name="" content="">
  <meta name="author" content="Andrew Spano">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="{% static '//fonts.googleapis.com/css?family=Raleway:400,300,600' %}" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'blog/normalize.css' %}"/>
  <link rel="stylesheet" href="{% static 'blog/skeleton.css' %}"/>

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'blog/images/favicon.png' %}"/>


</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <div class="row">
      <div class="eleven columns">
        <h1>Programmer Plebeian</h1>

	<ul>
	  {% if latest_post_list %}
	  {% for post in latest_post_list %}
	  <li><a href="{% url 'blog:view_post' post.id %}">{{post.content}}</a></li>
	  {% endfor %}
	</ul>
	{% else %}
	<p>There is no blog post available here</p>
	{% endif %}
	Hello World!!

      </div>
    </div>
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

blog/templates/blog/posts.html
{% load staticfiles %}

<h1>{{post.title_text}}</h1>
<ul>
  <body>
    <p>
      {{post.content}}
    </p>